USE 教务系统;
GO

ALTER DATABASE 教务系统
MODIFY FILE (
    NAME = TEACHER,
    MAXSIZE = 300MB,
    FILEGROWTH = 40MB
) --TO FILEGROUP GROUP1;

ALTER DATABASE 教务系统
MODIFY FILE (
    NAME = STUDENT,
    MAXSIZE = 300MB,
    FILEGROWTH = 40MB
) --TO FILEGROUP GROUP1;

ALTER DATABASE 教务系统
MODIFY FILE (
    NAME = COURSE,
    MAXSIZE = 300MB,
    FILEGROWTH = 40MB
) --TO FILEGROUP GROUP1;
