USE 教务系统;
GO

ALTER DATABASE 教务系统
ADD FILEGROUP GROUP1;

ALTER DATABASE 教务系统
ADD FILE (
    NAME = TEACHER,
    FILENAME = 'E:\database\TEACHER.ndf',
    SIZE = 60MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 30%
) TO FILEGROUP GROUP1;

ALTER DATABASE 教务系统
ADD FILE (
    NAME = STUDENT,
    FILENAME = 'E:\database\STUDENT.ndf',
    SIZE = 60MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 30%
) TO FILEGROUP GROUP1;

ALTER DATABASE 教务系统
ADD FILE (
    NAME = COURSE,
    FILENAME = 'E:\database\COURSE.ndf',
    SIZE = 60MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 30%
) TO FILEGROUP GROUP1;
